### ISSUE TITLE
Mobile responsiveness

### ISSUE THREAD

**Issue by Boby900** [Boby900/books-keeper#1]
Hey there,
I am trying to make it mobile responsive but not able to, if you could make my form section look good on mobile that would be awesome.
Any kind of help would be highly admirable.

**PFA**
![Screenshot (166)](https://github.com/Boby900/books-keeper/assets/111265239/480a6799-7c4d-4265-ac40-7dc46d9f1642)

**Comment by Sky-De** [comment]
@Boby900 hi, i would like to work on this , please assign this to me ,
thanks

**Comment by Sky-De** [comment]
@Boby900 this is the result of my work on this issue

![form-desktop](https://github.com/Boby900/books-keeper/assets/79264045/d69604b2-6b1f-45d8-825b-9b9f69f9baaa)
![form-mobile](https://github.com/Boby900/books-keeper/assets/79264045/5b6e932c-504b-4fa3-8205-e1fe021e1ec7)


as soon as i get assignment i will create PR for these changes
Thanks

**Comment by Boby900** [comment]
hey @Sky-De I have assigned this issue to you thanks for your time and efforts which you have put in 👍

**Comment by Sky-De** [comment]
@Sky-De no problem, thanks for assignment , i will send PR now
